### PR TITLE
[move-book and move-book-zh] Fix zh translation

### PR DESCRIPTION
**Pull request by Kusou1**
## Motivation
There are also some small mistakes left over from before,i correct them

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?
Yes

### CODE REVIEW

**Review by Kusou1 — COMMENTED** [review]
Review

**Comment by Kusou1** [comment]
@sblackshear

**Review by geometryolife — COMMENTED** [review]
Already review

**Review by Kusou1 — COMMENTED** [review]
Review

**Review by sblackshear — APPROVED** [review]
LGTM, but some merge conflicts need to be fixed

**Comment by wrwg** [comment]
Can you please resolve the conflicts and re-submit?

**Comment by Kusou1** [comment]
> Can you please resolve the conflicts and re-submit?

ok,i will resolve the conflicts

**Comment by geometryolife** [comment]
> > Can you please resolve the conflicts and re-submit?
> 
> ok,i will resolve the conflicts

I've fixed this and it's already been merged into the main branch in #543
@wrwg @Kusou1

**Pull request closed without merging**
