### PR TITLE
[Prover] Bump up the version number of Boogie

### PR DESCRIPTION
**Pull request by junkil-park**
- Upgrade Boogie to 2.15.8.

## Motivation

Upgrade the Prover's dependency

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

yes

## Test Plan

cargo test

### CODE REVIEW

**Comment by meng-xu-cs** [comment]
There are known non-determinism in these test cases:

```
    prover unit[default]::functional/loops_with_memory_ops.move
    prover unit[default]::functional/loops.move
```

I guess updating Boogie / Z3 accidentally causes the random number to go from one side to the other side (i.e., concretizing variable `x` vs variable `y`). Maybe we should disable them or re-write them into deterministic way?

**Comment by wrwg** [comment]
Let's wait with this until we know whether the new boogie fixes our problem. If so, this PR should also increase the minimal boogie number required in the prover driver.

**Review by wrwg — APPROVED** [review]
Can we cherry pick this in the `aptos` branch? Otherwise we wont have it in the `aptos` CLI.

Let me know if its unclear how to do this.

**Comment by junkil-park** [comment]
> Can we cherry pick this in the `aptos` branch? Otherwise we wont have it in the `aptos` CLI.
> 
> Let me know if its unclear how to do this.

@wrwg , I put up a PR to cherry pick this: https://github.com/move-language/move/pull/535

**Pull request merged**
