### PR TITLE
MoveValueAnnotator: get_type_layout_*

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

Expose MoveTypeLayout from the MoveValueAnnotaor. This can be got elsewhere, but the callsite I'm focusing on has this annotator, and it'll be nice if the cache inside can be leveraged.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan
https://github.com/aptos-labs/aptos-core/pull/568 introduced unit tests to utilize this.

### CODE REVIEW

**Review by wrwg — APPROVED** [review]

**Comment by msmouse** [comment]
It unitests fail to compile, seeing the same on other PRs as well, and it takes long to rail the compile.. guessing low memory? :(

**Comment by msmouse** [comment]
@tnowacki  I suspect the compile failure is due to lack of memory. Possible to increase memory limit?

**Comment by wrwg** [comment]
Alden, please join the discord channel(s) to discuss this issue if you have not yet. DaveW can provide invite links.

This is an old problem which Brendan and I had hoped to solve when the repo was moved. It's the low provisioning we have on GH (2 cores, 7g). 

Since other PRs did merge today, I wonder whether you have added any new deps?

**Comment by msmouse** [comment]
```
move-bytecode-utils = { path = "../move-bytecode-utils" } 
```
this internal dep was added to the move-resource-viewer 😞

**Pull request merged**
