### PR TITLE
upgrade rust toolchain 1.62.1  && edition 2021 && cargo clippy --fix

### PR DESCRIPTION
**Pull request by uvd**
## Motivation

upgrade rust toolchain 1.62.1 && cargo clippy --fix

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

No

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]
Thanks!

**Comment by sblackshear** [comment]
Looks like upgrading introduces some lint errors which will need to be fixed: https://github.com/move-language/move/runs/7394171716

**Comment by uvd** [comment]
> Looks like upgrading introduces some lint errors which will need to be fixed: https://github.com/move-language/move/runs/7394171716

hello  i'm fix it

**Comment by wrwg** [comment]
This is really great, and sorry for the delay on landing! As it is now 10 days old, could we please rebase it and run again through CI? Even without merge conflicts there could be more lint errors now which people landed after @uvd did touch this last.

**Comment by uvd** [comment]
> This is really great, and sorry for the delay on landing! As it is now 10 days old, could we please rebase it and run again through CI? Even without merge conflicts there could be more lint errors now which people landed after @uvd did touch this last.

Hey ，I'm rebase it

**Pull request merged**
