### PR TITLE
migrate Move Book of Chinese version from MoveDao

### PR DESCRIPTION
**Pull request by geometryolife**
## Motivation

The *[MoveDao](https://github.com/move-dao) community* has a group of volunteers dedicated to maintaining the Chinese version of Move Book. In a short period of time, we have completed the translation and proofreading of Move Book.
We decided to migrate the translated content to `book/translations/move-book-zh`.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

yes

### CODE REVIEW

**Review by Kusou1 — COMMENTED** [review]
Review

**Comment by geometryolife** [comment]
Hi @sblackshear , this pr has been completed and needs your approval.

**Review by sblackshear — APPROVED** [review]

**Comment by geometryolife** [comment]
This check looks a bit odd and may require your manual merge @sblackshear

**Comment by sblackshear** [comment]
Looks like this lint error needs fixing:

```
Error:  [eof-newline] [content language/documentation/book/translations/move-book-zh/src/address.md]: missing newline at EOF
```

**Pull request merged**
