### PR TITLE
Print type tags in Debug::print

### PR DESCRIPTION
**Pull request by macalinao**
## Motivation

easier to read

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

WIP

### CODE REVIEW

**Comment by macalinao** [comment]
Incomplete but I'm trying to print strings in `Debug`-- i need to create some test cases

**Comment by sblackshear** [comment]
I think @vgao1996 (who added the VM debug printing logic IIRC), @runtian-zhou, or @tnowacki will be able to suggest a way to test this.

**Comment by runtian-zhou** [comment]
I don't have a nice suggestion for testing this at the moment. IIUC the debug printing logic is gated under the testing flag so you definitely can perform a one-shot testing by using `--features testing` for `cargo`. I'm not sure how to write a persistent unit test for this. Maybe @vgao1996 may have a better clue?

**Comment by vgao1996** [comment]
Sorry for the late reply and I welcome this change!

You can add your new test cases to https://github.com/move-language/move/tree/main/language/tools/move-cli/tests/sandbox_tests/print_values and run `env UPBL=1 cargo test` to update the .exp files. This should also take care of your existing test failure.

**Comment by wrwg** [comment]
Is this still active?

**Pull request closed without merging**
