### PR TITLE
[move-analyzer] Improve support for Move doc comments

### PR DESCRIPTION
**Pull request by macalinao**
## Motivation

Annoying to write doc strings

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

Ran the extension locally

### CODE REVIEW

**Comment by macalinao** [comment]
side note: can you guys switch to Prettier or move all formatting to ESLint? `tsfmt` is pretty rare

**Comment by wrwg** [comment]
Ping on this PR. @awelc is this correctly routed to you?

**Review by awelc — APPROVED** [review]
LGTM

**Comment by awelc** [comment]
> Ping on this PR. @awelc is this correctly routed to you?

I am sorry I missed it. It's related to VSCode extension which is why it was routed to me I suppose, though my main contributions there are on the language server (Rust) side.

Still, it seems like I am now the owner/maintainer here unless @vgao1996 wants to (re)claim the title :-)

**Pull request merged**
