### PR TITLE
[move-book-zh] change the translation of the `named address` in the Chinese

### PR DESCRIPTION
**Pull request by geometryolife**
## Motivation

Change the translation of the `named address`, make it more in line with the expressed meaning.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

### CODE REVIEW

**Comment by geometryolife** [comment]
@jolestar @emmazzz @runtian-zhou @meng-xu-cs 
Please help review, change to `具名地址` or keep `命名地址` as it is?

**Comment by jolestar** [comment]
貌似“具名”更合适一些？

**Comment by emmazzz** [comment]
agreed that “具名" is better

**Comment by runtian-zhou** [comment]
我个人更喜欢 `命名地址` 一些，具名有一点具体的意味在，但是named address本身是一个可以被（编译时）替换的东西，所以我可能觉得命名更合适一些吧

**Comment by geometryolife** [comment]
> 我个人更喜欢 `命名地址` 一些，具名有一点具体的意味在，但是named address本身是一个可以被（编译时）替换的东西，所以我可能觉得命名更合适一些吧

实际上这里的 `具名地址` 表达的是拥有名字的地址，”具“表达的含义是”具有、拥有“；`命名地址` 表达的是"被命名，被赋予名字"。我觉得两者区别不大，只是前者是主动，后者是被动的语态。

**Comment by geometryolife** [comment]
Let's keep the original `命名地址` translation.

**Pull request closed without merging**
