### PR TITLE
[move-package] Change all yaml files to be TOML

### PR DESCRIPTION
**Pull request by gregnazario**
## Motivation

Let's stick with 1 parser for Move.  I picked TOML, since it was the one that was already being manually manipulated for the Move package system.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

yes

## Test Plan

Ran tests, though the solidity ones didn't like me

## Related issue
https://github.com/move-language/move/issues/176

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
Agreed sticking to one format is much better,

Since the build tree is generated, this should not introduce a breaking change, so lets land it.

**Comment by villesundell** [comment]
Hello! :wave: The problem doesn't seem to be the EVM tests alone, since the CLI Docker image test (last in the list) also fails with "`Error: values must be emitted before tables`" (https://github.com/move-language/move/runs/6695042916). The same test seems to be successful in other PRs, such as this one: https://github.com/move-language/move/runs/6683370096.

**Comment by gregnazario** [comment]
> Hello! 👋 The problem doesn't seem to be the EVM tests alone, since the CLI Docker image test (last in the list) also fails with "`Error: values must be emitted before tables`" (https://github.com/move-language/move/runs/6695042916). The same test seems to be successful in other PRs, such as this one: https://github.com/move-language/move/runs/6683370096. (UPDATE: I was able to reproduce this issue by checking out gregnazario:toml-everywhere and following the [quickstart sequence](https://github.com/move-language/move#quickstart)).

I'll take a look at it, it's just very strange that changing these formats seems to have caused a different issue.

**Comment by wrwg** [comment]
> Error: values must be emitted before table

This is a serious issue with toml. May need to move fields which represent collections at the end of the underlying Rust struct definition.

**Comment by gregnazario** [comment]
Closing, this won't be changed in time.

**Pull request closed without merging**
